### PR TITLE
Update Git and GitHub setup instructions

### PR DESCRIPTION
**Pull request by Iain-S**
Add more detailed Git/GitHub instructions now that learners will need to use SSH keys for the latter

### CODE REVIEW

**Comment by jemrobinson** [comment]
This is great, but I think we'll need something similar for the `macOS` and `Windows` instructions too. Can you add that (or make a new document about Git and link to it from all three?

**Comment by Iain-S** [comment]
Of course, I knew I needed to mention Git Bash somewhere. For now, I'll take the repetitive option and add the same section to all three, with minor tweaks.

**Comment by jemrobinson** [comment]
I'm away tomorrow and Friday but maybe @jack89roberts or @kasra-hosseini can merge this when you're ready @Iain-S ?

**Comment by kasra-hosseini** [comment]
Thanks @Iain-S , looks good to me.

**Review by kasra-hosseini — APPROVED** [review]

**Comment by Iain-S** [comment]
Great, I'll add the other instructions tomorrow and give Kasra a shout.

**Comment by Iain-S** [comment]
@kasra-hosseini there were already some GitHub setup instructions in the Windows file. I have overwritten them for consistency's sake but let me know if you think I should go back to the old instructions that say to use GitHub desktop client because  Windows users may be less familiar with the command-line.

**Comment by kasra-hosseini** [comment]
@Iain-S It is great that the instructions are now consistent across OS, but as you also said, I think it would be good to keep the instructions for `GitHub Desktop` (at least for Windows users). What about having two methods to set up Git/GitHub for Windows users? What do you think?

**Comment by Iain-S** [comment]
Agreed. Done.

**Comment by Iain-S** [comment]
I've squashed the commits to one per OS and will merge now in time for the start of the course, tomorrow.

**Comment by kasra-hosseini** [comment]
Sounds good. Thanks @Iain-S.

**Pull request merged**
