### PR TITLE
Correct the final checkout in the sequence diagram

### LINKED ISSUE #198: In 4.2, should `git checkout` update file from repo, not staging area?
In the last diagram in the notebook, my understanding (and from my tests) suggests that "Update file to reverted version" should be a line from repo to Jim, ie `R->J: Update file to reverted version`, rather than `I->J`.

### PR DESCRIPTION
**Pull request by Iain-S**
Closes #198

@jemrobinson I did a `git add -p` to only add the diagram code and rendered diagram contents. Is that the right/easiest way to do it? I presume that we don't want the new commit SHAs, etc. from me running modules 0-2?

### CODE REVIEW

**Review by jemrobinson — APPROVED** [review]
LGTM

**Comment by Iain-S** [comment]
Does it matter that the black linter is failing?

**Comment by jemrobinson** [comment]
I can't work out why it's failing. When I run locally it passes. Do you see the errors on your side?

**Comment by Iain-S** [comment]
Yep, this is what I get (abridged)

```shell
$ nbqa black module*/*.ipynb --nbqa-diff --verbose
...
reformatted module09_programming_for_speed/09_05_performance_scaling-Copy1.ipynb
module10_scientific_file_formats/10_03_binary_formats.ipynb already well formatted, good job.
reformatted module09_programming_for_speed/Untitled1.ipynb
module10_scientific_file_formats/10_02_deserialisation.ipynb already well formatted, good job.
All done! ✨ 🍰 ✨
11 files reformatted, 88 files left unchanged.
To apply these changes, remove the `--nbqa-diff` flag
```

**Pull request merged**
