### PR TITLE
Updates to module 5: Testing your Code

### PR DESCRIPTION
**Pull request by andrewphilipsmith**
This PR implements some of the changes recommended in #88 and #131.

### CODE REVIEW

**Comment by jemrobinson** [comment]
Is there anything else you want to include in this PR @andrewphilipsmith or is it ready to review?

**Comment by andrewphilipsmith** [comment]
> Is there anything else you want to include in this PR @andrewphilipsmith or is it ready to review?

No, not yet. I've switched it to draft.

**Comment by andrewphilipsmith** [comment]
I think that this can be merged. I will create a separate PR to look at the final example.

**Review by jemrobinson — APPROVED** [review]
LGTM. Merge when you're ready.

**Pull request merged**
